Work caleb
nwestervelt/chess-game pull request #10
Opened 2022-09-29 20:57 UTC by CalebStadler

Added in capturing and the ability for the king to castle with the rook. Made modifications to multiple files so please take a look over them all and leave your feedback.

2022-09-29 22:43 UTC, nwestervelt requested changes
Please review my comments and make the recommended changes.

If any of the recommended changes don't work, or you feel that the recommended changes were made in error, please discuss it with me.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
> +    protected void capturePiece(int occupyingPiece, PieceAbstract[] pieces)
I think right here, we could pass the particular piece being captured instead of the entire array and the occupyingPiece variable.

The new method signature could look like:
    protected void capturePiece(PieceAbstract piece)

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
>                  //check if player is attempting to move ontop of their own piece
Modify this comment to reflect the new state of this 'if' statement.

New comment could look like:
//if attempting to move onto a space already occupied

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
>                  //check if player is attempting to move ontop of their own piece
Modify this comment to reflect the new state of this 'if' statement. This also applies to the other chess piece files that contain this if statement and comment.

New comment could look like:
//if attempting to move onto a space already occupied

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
> +    private boolean notMoved = true;
I don't think it was necessary to declare this in the abstract class.

This variable was already declared in the Pawn, King, and Rook classes, where it is used. See my comments on the King class for more details.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
> +    public boolean getNotMoved()
This method should've been declared inside the Rook class, the only class that needs it.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/Rook.java
> -    private boolean notMoved = true;
This was an unnecessary change, see my comments on the King class for more details.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/King.java
> +            for(int i = 0; i < pieces.length; i++)
You don't need to iterate over the whole array, just use the 'this' keyword to reference 'this' King object.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/King.java
> +                if(pieces[i].getX() == this.x && pieces[i].getY() == this.y)
Refer to above comment, this test is unnecessary.

2022-09-29 22:43 UTC, nwestervelt commented on ChessPiece/King.java
> +                    if(x - this.x == -2 && pieces[i - 3].getNotMoved())
Here, if you cast 'pieces[i - 3]' to the Rook type, you'll be able to access methods declared directly inside the Rook class.

What the cast could look like:
((Rook)pieces[i - 3]).getNotMoved()

2022-09-30 00:43 UTC, CalebStadler commented on ChessPiece/PieceAbstract.java
> +    protected void capturePiece(int occupyingPiece, PieceAbstract[] pieces)
I don't think that this is necessary since all the method calls would need to be changed in each class

2022-09-30 01:10 UTC, nwestervelt commented on King.java
> +                            this.notMoved = false;
The 'this' keyword isn't needed here, or on lines 89 and 99.
```suggestion
                            notMoved = false;
```

2022-09-30 19:08 UTC, nwestervelt commented on ChessPiece/PieceAbstract.java
> +    protected void capturePiece(int occupyingPiece, PieceAbstract[] pieces)
It is true that the method call in each class would need to be changed, but it would also reduce the amount of data being passed between the classes.

2022-09-30 19:14 UTC, nwestervelt approved these changes

2022-09-30 19:16 UTC, merged