Fix Rook Movement and Menu Bugs
nwestervelt/chess-game pull request #22
Opened 2022-11-01 19:56 UTC by CalebStadler

Fixed the bug where if the rook tried to move on to its own square it would not throw and exception and fixed bug where the menu for captured pieces was not being updated properly at the start of a new game.

2022-11-01 19:59 UTC, hidayat0411 commented
Dengan bug pazel broo

2022-11-01 23:09 UTC, nwestervelt commented on PieceAbstract.java
>      }
I suggest adding a comment here to match the other methods.
```Suggestion
    }
    //used to reset the captured piece counts back to 0
```

2022-11-01 23:12 UTC, nwestervelt requested changes
See my comment for the change I'm requesting.

Overall it looks good.

2022-11-01 23:47 UTC, nwestervelt approved these changes

2022-11-01 23:48 UTC, merged

2022-12-08 16:19 UTC, hidayat0411 reviewed
Helow gaes